-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MYYEBOOK
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MYYEBOOK
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MYYEBOOK` DEFAULT CHARACTER SET utf8 ;
USE `MYYEBOOK` ;

-- -----------------------------------------------------
-- Table `MYYEBOOK`.`AUTEUR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MYYEBOOK`.`AUTEUR` (
  `AUT_ID` INT NOT NULL,
  `AUT_NOM` VARCHAR(45) NOT NULL,
  `AUT_PRENOM` VARCHAR(45) NOT NULL,
  `AUT_IMG` VARCHAR(45) NULL,
  PRIMARY KEY (`AUT_ID`),
  UNIQUE INDEX `AUT_ID_UNIQUE` (`AUT_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MYYEBOOK`.`CATAGORIE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MYYEBOOK`.`CATAGORIE` (
  `CAT_ID` INT NOT NULL,
  `CAT_LIBELLE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CAT_ID`),
  UNIQUE INDEX `CAT_ID_UNIQUE` (`CAT_ID` ASC) VISIBLE,
  UNIQUE INDEX `CAT_LIBELLE_UNIQUE` (`CAT_LIBELLE` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MYYEBOOK`.`LIVRE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MYYEBOOK`.`LIVRE` (
  `LIV_ID` INT NOT NULL,
  `LIV_TITRE` VARCHAR(45) NOT NULL,
  `LIV_RESUME` TEXT(255) NOT NULL,
  `LIV_IMAGE` LONGBLOB NULL,
  `LIV_QUANTITE` INT NOT NULL,
  `AUTEUR_AUT_ID` INT NOT NULL,
  `CATAGORIE_CAT_ID` INT NOT NULL,
  PRIMARY KEY (`LIV_ID`),
  UNIQUE INDEX `LIV_ID_UNIQUE` (`LIV_ID` ASC) VISIBLE,
  INDEX `fk_LIVRE_AUTEUR1_idx` (`AUTEUR_AUT_ID` ASC) VISIBLE,
  INDEX `fk_LIVRE_CATAGORIE1_idx` (`CATAGORIE_CAT_ID` ASC) VISIBLE,
  CONSTRAINT `fk_LIVRE_AUTEUR1`
    FOREIGN KEY (`AUTEUR_AUT_ID`)
    REFERENCES `MYYEBOOK`.`AUTEUR` (`AUT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LIVRE_CATAGORIE1`
    FOREIGN KEY (`CATAGORIE_CAT_ID`)
    REFERENCES `MYYEBOOK`.`CATAGORIE` (`CAT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MYYEBOOK`.`COMPTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MYYEBOOK`.`COMPTE` (
  `SEC_ID` INT NOT NULL,
  `SEC_LOGIN` CHAR(10) NOT NULL,
  `SEC_PASS` CHAR(255) NOT NULL,
  UNIQUE INDEX `SEC_ID_UNIQUE` (`SEC_ID` ASC) VISIBLE,
  PRIMARY KEY (`SEC_ID`),
  UNIQUE INDEX `SEC_LOGIN_UNIQUE` (`SEC_LOGIN` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MYYEBOOK`.`CLIENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MYYEBOOK`.`CLIENT` (
  `CLI_ID` INT NOT NULL,
  `CLI_NOM` VARCHAR(45) NOT NULL,
  `CLI_PRENOM` VARCHAR(45) NOT NULL,
  `CLI_EMAIL` VARCHAR(100) NOT NULL,
  `COMPTE_SEC_ID` INT NOT NULL,
  PRIMARY KEY (`CLI_ID`),
  UNIQUE INDEX `CLI_ID_UNIQUE` (`CLI_ID` ASC) VISIBLE,
  INDEX `fk_CLIENT_COMPTE1_idx` (`COMPTE_SEC_ID` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENT_COMPTE1`
    FOREIGN KEY (`COMPTE_SEC_ID`)
    REFERENCES `MYYEBOOK`.`COMPTE` (`SEC_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MYYEBOOK`.`LIBRAIRE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MYYEBOOK`.`LIBRAIRE` (
  `LIB_ID` INT NOT NULL,
  `LIB_NOM` VARCHAR(45) NOT NULL,
  `LIB_PRENOM` VARCHAR(45) NOT NULL,
  `COMPTE_SEC_ID` INT NOT NULL,
  PRIMARY KEY (`LIB_ID`),
  UNIQUE INDEX `LIB_ID_UNIQUE` (`LIB_ID` ASC) VISIBLE,
  INDEX `fk_LIBRAIRE_COMPTE1_idx` (`COMPTE_SEC_ID` ASC) VISIBLE,
  CONSTRAINT `fk_LIBRAIRE_COMPTE1`
    FOREIGN KEY (`COMPTE_SEC_ID`)
    REFERENCES `MYYEBOOK`.`COMPTE` (`SEC_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MYYEBOOK`.`CLIENT_has_LIVRE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MYYEBOOK`.`CLIENT_has_LIVRE` (
  `CLIENT_CLI_ID` INT NOT NULL,
  `LIVRE_LIV_ID` INT NOT NULL,
  `LIBRAIRE_LIB_ID` INT NOT NULL,
  PRIMARY KEY (`CLIENT_CLI_ID`, `LIVRE_LIV_ID`, `LIBRAIRE_LIB_ID`),
  INDEX `fk_CLIENT_has_LIVRE_LIVRE1_idx` (`LIVRE_LIV_ID` ASC) VISIBLE,
  INDEX `fk_CLIENT_has_LIVRE_CLIENT_idx` (`CLIENT_CLI_ID` ASC) VISIBLE,
  INDEX `fk_CLIENT_has_LIVRE_LIBRAIRE1_idx` (`LIBRAIRE_LIB_ID` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENT_has_LIVRE_CLIENT`
    FOREIGN KEY (`CLIENT_CLI_ID`)
    REFERENCES `MYYEBOOK`.`CLIENT` (`CLI_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENT_has_LIVRE_LIVRE1`
    FOREIGN KEY (`LIVRE_LIV_ID`)
    REFERENCES `MYYEBOOK`.`LIVRE` (`LIV_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENT_has_LIVRE_LIBRAIRE1`
    FOREIGN KEY (`LIBRAIRE_LIB_ID`)
    REFERENCES `MYYEBOOK`.`LIBRAIRE` (`LIB_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
